I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    e "You've created a new Ren'Py game."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "F:\Desktop (F)\renpy-6.99.13-sdk\renpy\bootstrap.py", line 305, in bootstrap
    renpy.main.main()
  File "F:\Desktop (F)\renpy-6.99.13-sdk\renpy\main.py", line 499, in main
    run(restart)
  File "F:\Desktop (F)\renpy-6.99.13-sdk\renpy\main.py", line 147, in run
    renpy.execution.run_context(True)
  File "F:\Desktop (F)\renpy-6.99.13-sdk\renpy\execution.py", line 795, in run_context
    context.run()
  File "game/script.rpy", line 28, in script
    e "You've created a new Ren'Py game."
  File "F:\Desktop (F)\renpy-6.99.13-sdk\renpy\ast.py", line 596, in execute
    who = eval_who(self.who, self.who_fast)
  File "F:\Desktop (F)\renpy-6.99.13-sdk\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'e' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
RenPy-hello-world 1.0
